### ISSUE TITLE
Allow the same versions of base and pandoc as BlogLiterately

### ISSUE THREAD

**Issue by idontgetoutmuch** [byorgey/BlogLiterately-diagrams#9]
BlogLitereately has `base (>=4.0 && <4.11)` and `pandoc (>=2.0 && <2.2)` but BlogLiterately-diagrams has `base (>=4.3 && <4.10)` and `pandoc (>=1.16 && <1.20)`

**Comment by byorgey** [comment]
Thanks for the nudge, I'll try to fix this soon.  It depends on `diagrams-builder` which is always a pain to upgrade, so we'll see how it goes!

**Comment by byorgey** [comment]
I've uploaded a new version to Hackage which should work --- it was easier than I thought.  Let me know if it works for you!

**Comment by idontgetoutmuch** [comment]
Hackage still says

> Uploaded | Sat Dec 3 20:31:54 UTC 2016 by BrentYorgey

???

**Comment by byorgey** [comment]
Oh!  Sorry, I keep forgetting that `cabal upload` now defaults to uploading a *candidate* package.
